version: "3.4"

services:
  # comment out `reverse-proxy` block if you don't wish to use https
  reverse-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/mysite.crt:/etc/nginx/mysite.crt:ro
      - ./certs/mysite.key:/etc/nginx/mysite.key:ro
    ports:
      - "3210:443"
    depends_on:
      - lobe-chat-https

  lobe-chat-https:
    image: lobehub/lobe-chat:latest
    restart: always
    # uncomment below if you don't wish to use https
    # ports:
    # - "3210:3210"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY?OPENAI_API_KEY not set}
      - ACCESS_CODE=${ACCESS_CODE?ACCESS_CODE not set}
